included: # paths to include during linting. `--path` is ignored if present.
  - Nexd
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
identifier_name:
  excluded:
    - id
nesting:
  type_level: 2 # allow view models to have nested view state
line_length: 180
function_body_length:
  - 100
  - 150
function_parameter_count:
  - 8
  - 15
function_parameter_count: 10
