name: Import Strings into POEditor

on:
  push:
    branches: [ develop ]
    paths:
      - 'Nexd/**/Localizable.strings'

jobs:
  poeditor:
    runs-on: ubuntu-latest
    steps:
      - name: English
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_POEDITOR_UPLOAD_ENGLISH }}
          data: ""

      - name: German
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_POEDITOR_UPLOAD_GERMAN }}
          data: ""

      # update ios translations from POEditor

      - name: Update Android English
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_POEDITOR_ANDROID_ENGLISH }}
          data: ""

      - name: Update Android English
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_POEDITOR_ANDROID_GERMAN }}
          data: ""
