name: TestFlight

on:
  push:
    branches: [ develop ]

jobs:
  testflight:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      run: |
        env
        cd Nexd
        bundle install
        bundle exec fastlane testflight_beta
